import type { Vehicle } from '@/types'

export const mockVehicles: Vehicle[] = [
  {
    id: 'mock-1',
    slug: '2022-toyota-camry-xse',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    trim: 'XSE',
    price: 28995,
    mileage: 22000,
    condition: 'USED',
    bodyStyle: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engine: '2.5L 4-Cylinder',
    exteriorColor: 'Midnight Black',
    interiorColor: 'Black',
    vin: '4T1BZ1HK5NU090001',
    description:
      'One owner, accident-free. Loaded with leather, sunroof, and safety package.',
    features: ['Sunroof', 'Leather Seats', 'Backup Camera', 'Apple CarPlay', 'Lane Departure Warning'],
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    ],
    status: 'AVAILABLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-2',
    slug: '2021-honda-cr-v-exl',
    make: 'Honda',
    model: 'CR-V',
    year: 2021,
    trim: 'EX-L',
    price: 31500,
    mileage: 35000,
    condition: 'USED',
    bodyStyle: 'SUV',
    transmission: 'CVT',
    fuelType: 'Gasoline',
    engine: '1.5L Turbocharged 4-Cylinder',
    exteriorColor: 'Lunar Silver',
    interiorColor: 'Gray',
    vin: '7FARW2H87ME000002',
    description:
      'Family-friendly AWD SUV with heated seats and Honda Sensing suite.',
    features: ['AWD', 'Heated Seats', 'Honda Sensing', 'Wireless CarPlay', 'Power Liftgate'],
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    ],
    status: 'AVAILABLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-3',
    slug: '2023-ford-f150-xlt',
    make: 'Ford',
    model: 'F-150',
    year: 2023,
    trim: 'XLT',
    price: 42000,
    mileage: 8500,
    condition: 'USED',
    bodyStyle: 'Truck',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engine: '2.7L EcoBoost V6',
    exteriorColor: 'Oxford White',
    interiorColor: 'Medium Light Slate',
    vin: '1FTFW1ED7PFC00003',
    description: 'Nearly new F-150 XLT with tow package and SYNC 4.',
    features: ['Tow Package', 'SYNC 4', 'Co-Pilot360', 'FordPass Connect', 'Pro Power Onboard'],
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    status: 'AVAILABLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-4',
    slug: '2020-bmw-3-series-330i',
    make: 'BMW',
    model: '3 Series',
    year: 2020,
    trim: '330i',
    price: 36900,
    mileage: 42000,
    condition: 'USED',
    bodyStyle: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engine: '2.0L Turbocharged 4-Cylinder',
    exteriorColor: 'Alpine White',
    interiorColor: 'Cognac',
    vin: 'WBA5R1C52KAK12345',
    description: 'Sporty, luxurious BMW 330i with premium package and driver assistance.',
    features: ['Premium Package', 'Navigation', 'Heated Seats', 'Parking Sensors', 'LED Headlights'],
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    ],
    status: 'AVAILABLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-5',
    slug: '2023-hyundai-tucson-sel',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    trim: 'SEL',
    price: 29400,
    mileage: 11000,
    condition: 'CERTIFIED',
    bodyStyle: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engine: '2.5L 4-Cylinder',
    exteriorColor: 'Phantom Black',
    interiorColor: 'Black',
    vin: 'KM8JBCD17PU000555',
    description: 'Certified Pre-Owned Tucson SEL. Balance of factory warranty included.',
    features: ['AWD', 'Blind-Spot Monitoring', 'Lane Keeping Assist', 'Wireless CarPlay', 'Sunroof'],
    images: [
      'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80',
    ],
    status: 'AVAILABLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-6',
    slug: '2024-chevrolet-silverado-lt',
    make: 'Chevrolet',
    model: 'Silverado 1500',
    year: 2024,
    trim: 'LT',
    price: 48500,
    mileage: 3200,
    condition: 'NEW',
    bodyStyle: 'Truck',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engine: '5.3L V8',
    exteriorColor: 'Northsky Blue',
    interiorColor: 'Jet Black',
    vin: '3GCPACED5RG000777',
    description: 'Brand new 2024 Silverado LT with trailering package and multi-flex tailgate.',
    features: ['Trailering Package', 'Multi-Flex Tailgate', 'Chevy Safety Assist', 'MyLink Radio', '4WD'],
    images: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80',
    ],
    status: 'AVAILABLE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
