// SEO Configuration for Naples, FL Car Dealer
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'
const DEALER_NAME = process.env.NEXT_PUBLIC_DEALER_NAME ?? 'E&S Car Sales'
const DEALER_PHONE = process.env.NEXT_PUBLIC_DEALER_PHONE ?? '+1 (941) 499-7415'
const DEALER_EMAIL = process.env.NEXT_PUBLIC_DEALER_EMAIL ?? 'info@eandscars.com'

// Default share image, generated by src/app/opengraph-image.tsx
export const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`
export const LOGO_URL = `${SITE_URL}/logo-512.png`

// Naples, FL location details for local SEO.
// Keep NAP (name/address/phone) identical to the Google Business Profile.
export const LOCATION = {
  streetAddress: '1029 Airport-Pulling Rd, Unit C 49',
  city: 'Naples',
  state: 'Florida',
  stateCode: 'FL',
  zipCode: '34104',
  county: 'Collier County',
  // Exact map pin from the Google Business Profile; geo schema is omitted while null
  geo: null as { latitude: number; longitude: number } | null,
  nearbyAreas: ['Marco Island', 'Bonita Springs', 'Fort Myers', 'Estero', 'Golden Gate', 'Immokalee'],
  serviceArea: 'Southwest Florida',
}

// ═══════════════════════════════════════════════════════════════════
// Vehicle SEO Helpers
// ═══════════════════════════════════════════════════════════════════

export function buildVehicleTitle(
  year: number,
  make: string,
  model: string,
  trim?: string | null
) {
  const base = trim ? `${year} ${make} ${model} ${trim}` : `${year} ${make} ${model}`
  return `${base} for Sale in Naples FL | ${DEALER_NAME}`
}

// JSON-LD for <script> tags: escape "<" so values like "</script>" can't break out of the tag
export function serializeJsonLd(data: unknown) {
  return JSON.stringify(data).replace(/</g, '\\u003c')
}

// URL-safe slug for make/model/body-style landing pages ("Mercedes-Benz" → "mercedes-benz")
export function slugify(value: string) {
  return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}

export const INVENTORY_LANDING_ROOT = '/cars-for-sale'

export function makePath(make: string) {
  return `${INVENTORY_LANDING_ROOT}/${slugify(make)}`
}

export function modelPath(make: string, model: string) {
  return `${INVENTORY_LANDING_ROOT}/${slugify(make)}/${slugify(model)}`
}

export function bodyStylePath(bodyStyle: string) {
  return `${INVENTORY_LANDING_ROOT}/type/${slugify(bodyStyle)}`
}

export const DEALER_ADDRESS = `${LOCATION.streetAddress}, ${LOCATION.city}, ${LOCATION.stateCode} ${LOCATION.zipCode}`

// Canonical VDP path: VIN when present, slug otherwise
export function vehiclePath(vehicle: { vin?: string | null; slug: string }) {
  return `/inventory/${vehicle.vin || vehicle.slug}`
}

export function vehicleUrl(vehicle: { vin?: string | null; slug: string }) {
  return `${SITE_URL}${vehiclePath(vehicle)}`
}

// Stock number shown on cards/VDPs and used as schema sku
export function stockNumber(vehicle: { vin?: string | null; id: string }) {
  return vehicle.vin ? `A${vehicle.vin.slice(-5).toUpperCase()}` : `S${vehicle.id.slice(-5).toUpperCase()}`
}

// Single source of truth for hours: schema, FAQ, footer, contact, and about pages all read from here.
// Must match the Google Business Profile exactly.
export const BUSINESS_HOURS = [
  { days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], label: 'Mon – Sat', opens: '09:00', closes: '19:00', display: '9am – 7pm' },
  { days: ['Sunday'], label: 'Sun', opens: '11:00', closes: '17:00', display: '11am – 5pm' },
]

function buildOpeningHours() {
  return BUSINESS_HOURS.map(({ days, opens, closes }) => ({
    '@type': 'OpeningHoursSpecification',
    dayOfWeek: days,
    opens,
    closes,
  }))
}

function buildGeo() {
  return LOCATION.geo
    ? { '@type': 'GeoCoordinates', latitude: LOCATION.geo.latitude, longitude: LOCATION.geo.longitude }
    : undefined
}

export function buildVehicleDescription(
  year: number,
  make: string,
  model: string,
  price: number,
  mileage: number
) {
  return `${year} ${make} ${model} for sale at ${DEALER_NAME} in Naples, FL. Price: $${price.toLocaleString()}. Mileage: ${mileage.toLocaleString()} miles. Visit our Naples dealership or browse our full inventory online. Serving Southwest Florida.`
}

export function buildVehicleKeywords(
  year: number,
  make: string,
  model: string,
  condition: string
) {
  const conditionText = condition.toLowerCase()
  return [
    `${year} ${make} ${model}`,
    `${make} ${model} for sale`,
    `${conditionText} ${make} ${model}`,
    `${make} dealer Naples FL`,
    `${make} ${model} Naples Florida`,
    `buy ${make} ${model}`,
    `${conditionText} cars Naples FL`,
    `car dealership Naples`,
  ].join(', ')
}

// Schema.org requires valid absolute URLs: resolve relative paths and percent-encode spaces
// ("WhatsApp Image 1.jpeg" → "WhatsApp%20Image%201.jpeg") without double-encoding existing escapes
export function absoluteImageUrl(src: string) {
  try {
    return new URL(src.trim(), SITE_URL).href
  } catch {
    return undefined
  }
}

// Trimmed string or undefined, so empty DB values never appear in structured data
function text(value?: string | null) {
  const trimmed = value?.trim()
  return trimmed ? trimmed : undefined
}

// "2.5L 4-Cylinder" → 2.5 litres; returns undefined when no displacement is stated
function parseEngineDisplacement(engine: string) {
  const match = engine.match(/(\d+(?:\.\d+)?)\s*L\b/i)
  return match ? { '@type': 'QuantitativeValue', value: Number(match[1]), unitCode: 'LTR' } : undefined
}

export function buildVehicleJsonLd(vehicle: {
  id: string
  slug: string
  make: string
  model: string
  year: number
  price: number
  images: string[]
  description?: string | null
  vin?: string | null
  mileage: number
  condition: string
  status?: string
  trim?: string | null
  fuelType?: string | null
  transmission?: string | null
  exteriorColor?: string | null
  interiorColor?: string | null
  bodyStyle?: string | null
  engine?: string | null
}) {
  const url = vehicleUrl(vehicle)
  const name = [vehicle.year, vehicle.make, vehicle.model, text(vehicle.trim)].filter(Boolean).join(' ')
  // Certified pre-owned has no schema.org condition of its own; it is UsedCondition
  const itemCondition = vehicle.condition === 'NEW' ? 'https://schema.org/NewCondition' : 'https://schema.org/UsedCondition'
  const availability =
    vehicle.status === 'SOLD'
      ? 'https://schema.org/SoldOut'
      : vehicle.status === 'PENDING'
        ? 'https://schema.org/LimitedAvailability'
        : 'https://schema.org/InStock'
  const images = [...new Set(vehicle.images.map(absoluteImageUrl).filter((src): src is string => Boolean(src)))]
  const engine = text(vehicle.engine)
  const fuelType = text(vehicle.fuelType)

  return {
    '@context': 'https://schema.org',
    // Product + Car makes the VDP eligible for Google vehicle/merchant listings
    '@type': ['Product', 'Car'],
    '@id': `${url}#vehicle`,
    url,
    name,
    description: text(vehicle.description) ?? `${name} for sale at ${DEALER_NAME} in ${LOCATION.city}, ${LOCATION.stateCode}.`,
    sku: stockNumber(vehicle),
    image: images.length > 0 ? images : undefined,

    brand: { '@type': 'Brand', name: vehicle.make },
    model: vehicle.model,
    modelDate: String(vehicle.year),
    vehicleModelDate: String(vehicle.year),
    vehicleConfiguration: text(vehicle.trim),
    vehicleIdentificationNumber: text(vehicle.vin),
    itemCondition,

    bodyType: text(vehicle.bodyStyle),
    mileageFromOdometer: { '@type': 'QuantitativeValue', value: vehicle.mileage, unitCode: 'SMI' },
    vehicleEngine: engine
      ? { '@type': 'EngineSpecification', name: engine, engineDisplacement: parseEngineDisplacement(engine), fuelType }
      : undefined,
    fuelType,
    vehicleTransmission: text(vehicle.transmission),
    color: text(vehicle.exteriorColor),
    vehicleInteriorColor: text(vehicle.interiorColor),

    // Google rejects offers without a positive price, so "call for price" vehicles omit the offer
    offers:
      vehicle.price > 0
        ? {
            '@type': 'Offer',
            url,
            price: vehicle.price,
            priceCurrency: 'USD',
            itemCondition,
            availability,
            priceValidUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            seller: {
              '@type': 'AutoDealer',
              '@id': `${SITE_URL}/#organization`,
              name: DEALER_NAME,
              telephone: DEALER_PHONE,
              address: buildPostalAddress(),
            },
          }
        : undefined,
  }
}

// ═══════════════════════════════════════════════════════════════════
// Dealer / Business SEO Helpers
// ═══════════════════════════════════════════════════════════════════

function buildPostalAddress() {
  return {
    '@type': 'PostalAddress',
    streetAddress: LOCATION.streetAddress,
    addressLocality: LOCATION.city,
    addressRegion: LOCATION.stateCode,
    postalCode: LOCATION.zipCode,
    addressCountry: 'US',
  }
}

export function buildDealerJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'AutoDealer',
    '@id': `${SITE_URL}/#organization`,
    name: DEALER_NAME,
    url: SITE_URL,
    logo: LOGO_URL,
    image: LOGO_URL,
    telephone: DEALER_PHONE,
    email: DEALER_EMAIL,
    address: buildPostalAddress(),
    geo: buildGeo(),
    areaServed: [
      { '@type': 'City', name: LOCATION.city },
      ...LOCATION.nearbyAreas.map(area => ({ '@type': 'City', name: area })),
    ],
    openingHoursSpecification: buildOpeningHours(),
    priceRange: '$$',
    currenciesAccepted: 'USD',
    paymentAccepted: 'Cash, Credit Card, Financing',
    sameAs: [
      'https://www.instagram.com/eands_car_sales_llc',
      'https://www.tiktok.com/@gomez_car_sales',
    ],
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'Vehicle Inventory',
      itemListElement: [
        { '@type': 'Offer', itemOffered: { '@type': 'Car', name: 'New Vehicles' } },
        { '@type': 'Offer', itemOffered: { '@type': 'Car', name: 'Used Vehicles' } },
        { '@type': 'Offer', itemOffered: { '@type': 'Car', name: 'Certified Pre-Owned' } },
      ],
    },
  }
}

export function buildLocalBusinessJsonLd() {
  return {
    '@context': 'https://schema.org',
    // Same entity as buildDealerJsonLd (AutoDealer is a LocalBusiness subtype) so Google sees one business
    '@type': 'AutoDealer',
    '@id': `${SITE_URL}/#organization`,
    name: DEALER_NAME,
    image: LOGO_URL,
    telephone: DEALER_PHONE,
    email: DEALER_EMAIL,
    url: SITE_URL,
    address: buildPostalAddress(),
    geo: buildGeo(),
    openingHoursSpecification: buildOpeningHours(),
  }
}

// ═══════════════════════════════════════════════════════════════════
// Breadcrumb SEO Helper
// ═══════════════════════════════════════════════════════════════════

export function buildBreadcrumbJsonLd(items: Array<{ name: string; url: string }>) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: item.url.startsWith('http') ? item.url : `${SITE_URL}${item.url}`,
    })),
  }
}

// ═══════════════════════════════════════════════════════════════════
// Inventory Page SEO Helper
// ═══════════════════════════════════════════════════════════════════

export function buildInventoryJsonLd(vehicles: Array<{
  slug: string
  vin?: string | null
  make: string
  model: string
  year: number
  price: number
  images: string[]
  mileage: number
  condition: string
}>, options: { name?: string; offset?: number } = {}) {
  const offset = options.offset ?? 0
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: options.name ?? `Vehicles for Sale at ${DEALER_NAME}`,
    numberOfItems: vehicles.length,
    itemListElement: vehicles.map((vehicle, index) => ({
      '@type': 'ListItem',
      position: offset + index + 1,
      url: vehicleUrl(vehicle),
      name: `${vehicle.year} ${vehicle.make} ${vehicle.model}`,
    })),
  }
}

// ═══════════════════════════════════════════════════════════════════
// FAQ SEO Helper (for contact/about pages)
// ═══════════════════════════════════════════════════════════════════

export function buildFAQJsonLd() {
  const faqs = [
    {
      question: 'What financing options do you offer?',
      answer: `At ${DEALER_NAME}, we offer flexible financing options for all credit situations. Get pre-approved in minutes with competitive rates. We work with multiple lenders to find the best terms for you.`,
    },
    {
      question: 'Do you accept trade-ins?',
      answer: 'Yes! We accept trade-ins and offer competitive market value for your current vehicle. The trade-in value can be applied directly to your new purchase.',
    },
    {
      question: 'Where are you located?',
      answer: `We are located at ${DEALER_ADDRESS}. We proudly serve Naples, Marco Island, Bonita Springs, Fort Myers, and all of Southwest Florida.`,
    },
    {
      question: 'What are your business hours?',
      answer: `We are open ${BUSINESS_HOURS.map((h) => `${h.label} ${h.display}`).join(', ')}.`,
    },
    {
      question: 'Do you offer test drives?',
      answer: 'Absolutely! Schedule a test drive online or call us at ' + DEALER_PHONE + '. We can work around your schedule to find a convenient time.',
    },
    {
      question: 'Are your vehicles inspected?',
      answer: 'Yes, every vehicle passes a comprehensive 150-point inspection before being listed. We ensure quality and reliability for all our customers.',
    },
  ]

  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(faq => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  }
}

// ═══════════════════════════════════════════════════════════════════
// Website SEO Helper
// ═══════════════════════════════════════════════════════════════════

export function buildWebsiteJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE_URL}/#website`,
    name: DEALER_NAME,
    url: SITE_URL,
    description: `${DEALER_NAME} - Your trusted car dealership in Naples, Florida. Browse new and used vehicles, get financing, and find your perfect car.`,
    publisher: {
      '@id': `${SITE_URL}/#organization`,
    },
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${SITE_URL}/inventory?make={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  }
}

// ═══════════════════════════════════════════════════════════════════
// Service Page JSON-LD Helpers
// ═══════════════════════════════════════════════════════════════════

export function buildFinancingJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'FinancialService',
    name: `Auto Financing at ${DEALER_NAME}`,
    description: 'Car financing for all credit situations in Naples, FL. Get pre-approved in minutes with competitive rates.',
    provider: {
      '@type': 'AutoDealer',
      name: DEALER_NAME,
      address: buildPostalAddress(),
      telephone: DEALER_PHONE,
    },
    areaServed: { '@type': 'City', name: 'Naples', containedInPlace: { '@type': 'State', name: 'Florida' } },
    url: `${SITE_URL}/financing`,
  }
}

export function buildTradeInJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name: `Vehicle Trade-In at ${DEALER_NAME}`,
    description: 'Get a competitive trade-in offer for your vehicle in Naples, FL. Instant value, applied directly to your next purchase.',
    provider: {
      '@type': 'AutoDealer',
      name: DEALER_NAME,
      address: buildPostalAddress(),
      telephone: DEALER_PHONE,
    },
    areaServed: { '@type': 'City', name: 'Naples', containedInPlace: { '@type': 'State', name: 'Florida' } },
    url: `${SITE_URL}/trade-in`,
  }
}

// ═══════════════════════════════════════════════════════════════════
// Page Metadata Helpers
// ═══════════════════════════════════════════════════════════════════

export const defaultMetadata = {
  siteName: DEALER_NAME,
  siteUrl: SITE_URL,
  locale: 'en_US',
  type: 'website' as const,
}

export function buildPageMetadata(options: {
  title: string
  description: string
  path?: string
  image?: string
  keywords?: string[]
  noIndex?: boolean
}) {
  const url = options.path ? `${SITE_URL}${options.path}` : SITE_URL
  const image = options.image ?? DEFAULT_OG_IMAGE

  return {
    title: options.title,
    description: options.description,
    keywords: options.keywords?.join(', '),
    alternates: {
      canonical: url,
    },
    openGraph: {
      title: options.title,
      description: options.description,
      url,
      siteName: DEALER_NAME,
      locale: 'en_US',
      type: 'website' as const,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: options.title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image' as const,
      title: options.title,
      description: options.description,
      images: [image],
    },
    robots: options.noIndex
      ? { index: false, follow: false }
      : { index: true, follow: true },
  }
}
