export const VEHICLE_MODELS: Record<string, string[]> = {
  Acura: ['ILX', 'TLX', 'RDX', 'MDX', 'NSX'],
  Audi: ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'RS3', 'RS5', 'RS7', 'S3', 'S4', 'S5'],
  BMW: ['2 Series', '3 Series', '4 Series', '5 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'M2', 'M3', 'M4', 'M5', 'i4', 'iX'],
  Buick: ['Enclave', 'Encore', 'Encore GX', 'Envision', 'LaCrosse'],
  Cadillac: ['CT4', 'CT5', 'Escalade', 'Escalade ESV', 'Lyriq', 'XT4', 'XT5', 'XT6'],
  Chevrolet: ['Blazer', 'Camaro', 'Colorado', 'Corvette', 'Equinox', 'Express', 'Malibu', 'Silverado 1500', 'Silverado 2500HD', 'Silverado 3500HD', 'Spark', 'Suburban', 'Tahoe', 'Trailblazer', 'Traverse', 'Trax'],
  Chrysler: ['300', 'Pacifica', 'Voyager'],
  Dodge: ['Challenger', 'Charger', 'Durango', 'Grand Caravan', 'Hornet'],
  Ford: ['Bronco', 'Bronco Sport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'F-250 Super Duty', 'F-350 Super Duty', 'Maverick', 'Mustang', 'Mustang Mach-E', 'Ranger', 'Transit'],
  Genesis: ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  GMC: ['Acadia', 'Canyon', 'Sierra 1500', 'Sierra 2500HD', 'Sierra 3500HD', 'Terrain', 'Yukon', 'Yukon XL'],
  Honda: ['Accord', 'Civic', 'CR-V', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline'],
  Hyundai: ['Elantra', 'Ioniq 5', 'Ioniq 6', 'Kona', 'Palisade', 'Santa Cruz', 'Santa Fe', 'Sonata', 'Tucson', 'Venue'],
  Infiniti: ['Q50', 'Q60', 'QX50', 'QX55', 'QX60', 'QX80'],
  Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Cherokee L', 'Grand Wagoneer', 'Renegade', 'Wagoneer', 'Wrangler'],
  Kia: ['Carnival', 'EV6', 'Forte', 'K5', 'Niro', 'Rio', 'Seltos', 'Soul', 'Sorento', 'Sportage', 'Stinger', 'Telluride'],
  Lexus: ['ES', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RX', 'TX', 'UX'],
  Lincoln: ['Aviator', 'Corsair', 'Nautilus', 'Navigator'],
  Mazda: ['CX-30', 'CX-5', 'CX-50', 'CX-70', 'CX-90', 'Mazda3', 'Mazda6', 'MX-5 Miata', 'MX-30'],
  'Mercedes-Benz': ['A-Class', 'AMG GT', 'C-Class', 'CLA', 'E-Class', 'EQB', 'EQE', 'EQS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class'],
  Nissan: ['Altima', 'Armada', 'Frontier', 'Kicks', 'Leaf', 'Maxima', 'Murano', 'Pathfinder', 'Rogue', 'Rogue Sport', 'Sentra', 'Titan', 'Versa', 'Z'],
  Ram: ['1500', '2500', '3500', 'ProMaster', 'ProMaster City'],
  Subaru: ['Ascent', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'Solterra', 'WRX'],
  Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y'],
  Toyota: ['4Runner', 'bZ4X', 'Camry', 'Corolla', 'Corolla Cross', 'GR Corolla', 'GR86', 'Highlander', 'Land Cruiser', 'Prius', 'RAV4', 'RAV4 Prime', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Venza'],
  Volkswagen: ['Atlas', 'Atlas Cross Sport', 'Golf', 'Golf GTI', 'ID.4', 'Jetta', 'Passat', 'Taos', 'Tiguan'],
  Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
}

export const VEHICLE_MAKES = Object.keys(VEHICLE_MODELS).sort()

// Record<make, Record<model, trim[]>>
export const VEHICLE_TRIMS: Record<string, Record<string, string[]>> = {
  Acura: {
    ILX: ['Base', 'Premium', 'Technology', 'A-Spec'],
    TLX: ['Base', 'Technology', 'A-Spec', 'Type S', 'Type S w/ Advance Package'],
    RDX: ['Base', 'Technology', 'A-Spec', 'Advance', 'PMC Edition'],
    MDX: ['Base', 'Technology', 'A-Spec', 'Advance', 'Type S', 'Type S Advance'],
    NSX: ['Base', 'Type S'],
  },
  Audi: {
    A3: ['Premium', 'Premium Plus', 'Prestige'],
    A4: ['Premium', 'Premium Plus', 'Prestige', 'S line'],
    A6: ['Premium', 'Premium Plus', 'Prestige'],
    A8: ['55 TFSI', 'L 55 TFSI', 'L 60 TFSI e'],
    Q3: ['Premium', 'Premium Plus', 'Prestige'],
    Q5: ['Premium', 'Premium Plus', 'Prestige', 'S line', 'SQ5 Premium', 'SQ5 Prestige'],
    Q7: ['Premium', 'Premium Plus', 'Prestige'],
    Q8: ['Premium', 'Premium Plus', 'Prestige', 'SQ8 Premium', 'SQ8 Prestige'],
    RS5: ['Sportback', 'Coupe'],
    S4: ['Premium', 'Premium Plus', 'Prestige'],
    S5: ['Sportback Premium', 'Sportback Premium Plus', 'Coupe Premium', 'Coupe Prestige'],
  },
  BMW: {
    '3 Series': ['330i', '330i xDrive', '330e', '330e xDrive', 'M340i', 'M340i xDrive'],
    '5 Series': ['530i', '530i xDrive', '540i', '540i xDrive', 'M550i xDrive'],
    'X3': ['sDrive30i', 'xDrive30i', 'M40i', 'xDrive30e'],
    'X5': ['sDrive40i', 'xDrive40i', 'xDrive45e', 'M50i', 'xDrive50e'],
    'X7': ['xDrive40i', 'xDrive50i', 'M60i'],
    'M3': ['Base', 'Competition', 'Competition xDrive'],
    'M4': ['Base', 'Competition', 'Competition xDrive'],
    'M5': ['Base', 'Competition'],
  },
  Chevrolet: {
    Blazer: ['LT', '2LT', 'RS', 'Premier'],
    Camaro: ['LS', 'LT', 'SS', 'ZL1', '1LE'],
    Colorado: ['WT', 'LT', 'Z71', 'ZR2', 'Trail Boss'],
    Equinox: ['LS', 'LT', 'RS', 'Premier'],
    Malibu: ['LS', 'RS', 'LT', 'Premier'],
    'Silverado 1500': ['WT', 'Custom', 'Custom Trail Boss', 'LT', 'LT Trail Boss', 'RST', 'LTZ', 'High Country'],
    'Silverado 2500HD': ['WT', 'Custom', 'LT', 'LTZ', 'High Country'],
    Suburban: ['LS', 'LT', 'RST', 'Z71', 'Premier', 'High Country'],
    Tahoe: ['LS', 'LT', 'RST', 'Z71', 'Premier', 'High Country'],
    Traverse: ['LS', 'LT', 'RS', 'Premier', 'High Country'],
  },
  Dodge: {
    Challenger: ['SXT', 'GT', 'R/T', 'R/T Scat Pack', 'SRT 392', 'SRT Hellcat', 'SRT Hellcat Redeye', 'Demon'],
    Charger: ['SXT', 'GT', 'R/T', 'R/T Scat Pack', 'SRT 392', 'SRT Hellcat', 'SRT Hellcat Redeye'],
    Durango: ['SXT', 'GT', 'Citadel', 'R/T', 'SRT 392', 'SRT Hellcat'],
  },
  Ford: {
    Bronco: ['Base', 'Big Bend', 'Black Diamond', 'Outer Banks', 'Badlands', 'Wildtrak', 'Everglades', 'Raptor'],
    'Bronco Sport': ['Base', 'Big Bend', 'Outer Banks', 'Badlands', 'Heritage'],
    Edge: ['SE', 'SEL', 'ST', 'Titanium'],
    Escape: ['S', 'SE', 'SEL', 'Titanium', 'ST-Line', 'Plug-In Hybrid'],
    Expedition: ['XL', 'XLT', 'Limited', 'Timberline', 'King Ranch', 'Platinum'],
    Explorer: ['Base', 'XLT', 'Timberline', 'Limited', 'ST', 'King Ranch', 'Platinum'],
    'F-150': ['Regular Cab XL', 'XLT', 'Lariat', 'King Ranch', 'Platinum', 'Limited', 'Raptor', 'Tremor', 'Lightning'],
    'F-250 Super Duty': ['XL', 'XLT', 'Lariat', 'King Ranch', 'Platinum', 'Limited', 'Tremor'],
    Maverick: ['XL', 'XLT', 'Lariat'],
    Mustang: ['EcoBoost', 'EcoBoost Premium', 'GT', 'GT Premium', 'Mach 1', 'Shelby GT500'],
    Ranger: ['XL', 'XLT', 'Lariat', 'Raptor'],
  },
  GMC: {
    Acadia: ['SL', 'SLE', 'SLT', 'AT4', 'Denali'],
    Canyon: ['Elevation', 'AT4', 'Denali'],
    'Sierra 1500': ['Pro', 'SLE', 'SLT', 'Elevation', 'AT4', 'AT4X', 'Denali', 'Denali Ultimate'],
    'Sierra 2500HD': ['Pro', 'SLE', 'SLT', 'AT4', 'Denali'],
    Terrain: ['SL', 'SLE', 'SLT', 'AT4', 'Denali'],
    Yukon: ['SLE', 'SLT', 'AT4', 'Denali', 'Denali Ultimate'],
    'Yukon XL': ['SLE', 'SLT', 'AT4', 'Denali', 'Denali Ultimate'],
  },
  Honda: {
    Accord: ['LX', 'Sport', 'Sport-L', 'EX-L', 'Touring', 'Hybrid Sport', 'Hybrid Touring'],
    Civic: ['LX', 'Sport', 'EX', 'EX-L', 'Touring', 'Si', 'Type R'],
    'CR-V': ['LX', 'EX', 'EX-L', 'Sport', 'Sport-L', 'Touring', 'Hybrid Sport', 'Hybrid Touring'],
    'HR-V': ['LX', 'Sport', 'EX', 'EX-L'],
    Odyssey: ['LX', 'EX', 'EX-L', 'Touring', 'Elite'],
    Passport: ['Sport', 'EX-L', 'TrailSport', 'Touring', 'Elite'],
    Pilot: ['Sport', 'EX-L', 'TrailSport', 'Touring', 'Elite', 'Black Edition'],
    Ridgeline: ['Sport', 'RTL', 'RTL-E', 'Black Edition'],
  },
  Hyundai: {
    Elantra: ['SE', 'SEL', 'N Line', 'Limited', 'N'],
    'Ioniq 5': ['SE Standard Range', 'SE', 'SEL', 'Limited'],
    'Ioniq 6': ['SE Standard Range', 'SE', 'SEL', 'Limited'],
    Kona: ['SE', 'SEL', 'N Line', 'Limited', 'N'],
    Palisade: ['SE', 'SEL', 'XRT', 'Limited', 'Calligraphy'],
    'Santa Fe': ['SE', 'SEL', 'XRT', 'Limited', 'Calligraphy'],
    Sonata: ['SE', 'SEL', 'SEL Plus', 'N Line', 'Limited'],
    Tucson: ['SE', 'SEL', 'XRT', 'Limited', 'N Line', 'Plug-In Hybrid'],
  },
  Jeep: {
    Cherokee: ['Latitude', 'Latitude Plus', 'Altitude', 'Limited', 'Trailhawk', 'Overland'],
    Compass: ['Sport', 'Latitude', 'Latitude Lux', 'Limited', 'Trailhawk'],
    Gladiator: ['Sport', 'Sport S', 'Willys', 'Overland', 'Rubicon', 'Mojave'],
    'Grand Cherokee': ['Laredo', 'Altitude', 'Limited', 'Overland', 'Summit', 'Trailhawk', '4xe', 'SRT', 'Trackhawk'],
    'Grand Cherokee L': ['Laredo', 'Altitude', 'Limited', 'Overland', 'Summit', 'Summit Reserve'],
    Wrangler: ['Sport', 'Sport S', 'Willys', 'Freedom', 'Sahara', 'Rubicon', '4xe', 'Rubicon 392'],
  },
  Kia: {
    Carnival: ['LX', 'LX+', 'EX', 'SX', 'SX Prestige'],
    EV6: ['Light', 'Standard', 'Wind', 'GT-Line', 'GT'],
    Forte: ['FE', 'LX', 'GT-Line', 'GT'],
    K5: ['LX', 'LXS', 'GT-Line', 'EX', 'GT'],
    Sorento: ['LX', 'S', 'EX', 'SX', 'SX Prestige', 'X-Line SX Prestige'],
    Sportage: ['LX', 'EX', 'SX', 'SX Prestige', 'X-Line', 'X-Line SX Prestige'],
    Telluride: ['LX', 'S', 'EX', 'SX', 'SX-P', 'X-Line', 'X-Pro', 'X-Pro SX Prestige'],
  },
  Lexus: {
    ES: ['250', '300h', '350'],
    GX: ['Premium', 'Luxury', 'Premium+', 'Overtrail', 'Luxury+'],
    IS: ['300', '300 AWD', '350', '350 AWD', '500 F Sport Performance'],
    NX: ['250', '350', '350h', '450h+'],
    RX: ['350', '350h', '500h F Sport Performance'],
    TX: ['350', '350h', '500h'],
    UX: ['200', '250h'],
  },
  Mazda: {
    'CX-5': ['S', 'S Select', 'S Preferred', 'S Premium', 'S Premium Plus', 'Turbo'],
    'CX-50': ['S', 'S Select', 'S Preferred', 'S Premium', 'Turbo', 'Turbo Premium', 'Turbo Premium Plus'],
    'CX-90': ['PHEV Select', 'PHEV Preferred', 'PHEV Premium', 'PHEV Premium Plus', 'e-Skyactiv Select', 'Turbo S'],
    Mazda3: ['Select', 'Preferred', 'Premium', '2.5 Turbo'],
    'MX-5 Miata': ['Sport', 'Club', 'Grand Touring'],
  },
  'Mercedes-Benz': {
    'C-Class': ['C 300', 'C 300 4MATIC', 'AMG C 43', 'AMG C 63'],
    'E-Class': ['E 350', 'E 350 4MATIC', 'E 450', 'E 450 4MATIC', 'AMG E 53', 'AMG E 63 S'],
    GLC: ['GLC 300', 'GLC 300 4MATIC', 'AMG GLC 43', 'AMG GLC 63'],
    GLE: ['GLE 350', 'GLE 350 4MATIC', 'GLE 450', 'AMG GLE 53', 'AMG GLE 63 S'],
    GLS: ['GLS 450', 'GLS 580', 'AMG GLS 63'],
    'S-Class': ['S 500', 'S 580', 'S 580 4MATIC', 'AMG S 63'],
  },
  Nissan: {
    Altima: ['S', 'SR', 'SV', 'SL', 'Platinum', 'SR AWD', 'Platinum AWD'],
    Armada: ['S', 'SV', 'SL', 'Platinum'],
    Frontier: ['S', 'SV', 'Pro-4X', 'PRO-X', 'SL'],
    Kicks: ['S', 'SV', 'SR'],
    Murano: ['S', 'SV', 'SL', 'Platinum'],
    Pathfinder: ['S', 'SV', 'SL', 'Rock Creek', 'Platinum'],
    Rogue: ['S', 'SV', 'SL', 'Platinum', 'Rock Creek'],
    Sentra: ['S', 'SV', 'SR'],
    Titan: ['S', 'SV', 'SL', 'Pro-4X', 'Platinum Reserve'],
  },
  Ram: {
    1500: ['Tradesman', 'HFE', 'Big Horn', 'Lone Star', 'Laramie', 'Rebel', 'Limited', 'Laramie Longhorn', 'Limited Longhorn', 'TRX'],
    2500: ['Tradesman', 'Big Horn', 'Lone Star', 'Laramie', 'Power Wagon', 'Limited', 'Laramie Longhorn', 'Limited Longhorn'],
    3500: ['Tradesman', 'Big Horn', 'Lone Star', 'Laramie', 'Limited', 'Laramie Longhorn', 'Limited Longhorn'],
  },
  Subaru: {
    Ascent: ['Base', 'Premium', 'Limited', 'Touring', 'Onyx Edition'],
    Crosstrek: ['Base', 'Premium', 'Limited', 'Sport', 'Wilderness'],
    Forester: ['Base', 'Premium', 'Sport', 'Limited', 'Touring', 'Wilderness'],
    Outback: ['Base', 'Premium', 'Limited', 'Limited XT', 'Touring', 'Touring XT', 'Wilderness', 'Onyx Edition XT'],
    WRX: ['Base', 'Premium', 'Limited', 'GT', 'tS'],
  },
  Tesla: {
    'Model 3': ['Rear-Wheel Drive', 'Long Range AWD', 'Performance'],
    'Model S': ['Plaid', 'Long Range'],
    'Model X': ['Plaid', 'Long Range'],
    'Model Y': ['Rear-Wheel Drive', 'Long Range AWD', 'Performance'],
    Cybertruck: ['Rear-Wheel Drive', 'All-Wheel Drive', 'Cyberbeast'],
  },
  Toyota: {
    '4Runner': ['SR5', 'SR5 Premium', 'TRD Sport', 'TRD Off-Road', 'TRD Off-Road Premium', 'Limited', 'TRD Pro'],
    Camry: ['LE', 'SE', 'SE Nightshade', 'XLE', 'XSE', 'TRD', 'XLE V6', 'XSE V6'],
    Corolla: ['L', 'LE', 'SE', 'XLE', 'XSE', 'Hybrid LE', 'Hybrid SE', 'GR Corolla'],
    'Corolla Cross': ['L', 'LE', 'S', 'XLE'],
    Highlander: ['L', 'LE', 'XLE', 'Limited', 'Platinum', 'Hybrid LE', 'Hybrid XLE', 'Hybrid Limited', 'Hybrid Platinum'],
    Prius: ['LE', 'XLE', 'Limited', 'Prime SE', 'Prime XSE', 'Prime XSE Premium', 'Prime Advanced'],
    RAV4: ['LE', 'XLE', 'XLE Premium', 'TRD Off-Road', 'Adventure', 'Limited', 'TRD', 'XLE Hybrid', 'SE Hybrid', 'XSE Hybrid', 'Limited Hybrid'],
    'RAV4 Prime': ['SE', 'XSE', 'XSE Technology'],
    Sequoia: ['SR5', 'Limited', 'Platinum', 'TRD Pro', 'Capstone'],
    Sienna: ['LE', 'XLE', 'Limited', 'Platinum', 'XSE'],
    Tacoma: ['SR', 'SR5', 'TRD Off-Road', 'TRD Sport', 'Limited', 'TRD Pro', 'Trail Edition', 'Trailhunter'],
    Tundra: ['SR', 'SR5', 'Limited', 'Platinum', '1794 Edition', 'TRD Pro', 'Capstone'],
    Venza: ['LE', 'XLE', 'Limited'],
  },
  Volkswagen: {
    Atlas: ['S', 'SE', 'SEL', 'SEL Premium', 'SE w/ Technology'],
    'Atlas Cross Sport': ['S', 'SE', 'SEL', 'SEL Premium'],
    'Golf GTI': ['S', 'SE', 'Autobahn'],
    'ID.4': ['Standard', 'S', 'Sport', 'Pro', 'Pro S', 'Pro S Plus', 'AWD Pro', 'AWD Pro S', 'AWD Pro S Plus'],
    Jetta: ['S', 'Sport', 'SE', 'SEL', 'GLI S', 'GLI Autobahn'],
    Taos: ['S', 'SE', 'SEL'],
    Tiguan: ['S', 'SE', 'SEL', 'SEL R-Line', 'SEL Premium'],
  },
  Volvo: {
    XC40: ['Core', 'Plus', 'Ultimate', 'Recharge Core', 'Recharge Plus', 'Recharge Ultimate'],
    XC60: ['Core', 'Plus', 'Ultimate', 'Recharge Core', 'Recharge Plus', 'Recharge Ultimate'],
    XC90: ['Core', 'Plus', 'Ultimate', 'Recharge Core', 'Recharge Plus', 'Recharge Ultimate'],
    S60: ['Core', 'Plus', 'Ultimate', 'Recharge Core', 'Recharge Plus', 'Recharge Ultimate'],
    S90: ['Core', 'Plus', 'Ultimate', 'Recharge Core', 'Recharge Plus', 'Recharge Ultimate'],
  },
}
